#!/bin/bash
rm *.o
as -g -o alloc.o  alloc.s
as -g -o read.o read.s
as -g -o write.o write.s
as -g -o read-records.o read-records.s
as -g -o write-records.o write-records.s
as -g -o count-chars.o count-chars.s
as -g -o write-newline.o write-newline.s
ld  write.o write-records.o count-chars.o write-newline.o -o write-records
ld  alloc.o read-records.o read.o count-chars.o write-newline.o -o read-records

as -g -o mem_mngr.o mem_mngr.s

ld -shared  -o mem_mngr.so mem_mngr.o 






